# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Pull Request Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4.1.7
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
      with:
        compiler: ldc-latest
  
    - name: "Get build dependencies"
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libsdl2-dev libfreetype6-dev
      
    - name: 'Check ImGui ABI and generated bindings'
      working-directory: vendor/i2d-imgui
      run: |
        bash tests/abi.sh
        ldc2 -run generator/generator.d
        git diff --exit-code -- source/i2d/imgui/bind/imgui.d

    - name: 'Build'
      run: |
        dub build --compiler=ldc2 --build=release --config=barebones
    
    - name: 'Test'
      run: |
        dub build --compiler=ldc2 --config=barebones --build=unittest --dest=build/unittest
        build/unittest/out/inochi-creator --DRT-testmode=test-or-main

    - name: "Upload Artifacts"  
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: inochi-creator
        path: out/inochi-creator
